/**
 * Refreshes the committed roles fallback.
 *
 *   SHEET_WEBHOOK=... node scripts/refresh-roles.mjs           (npm run roles:refresh)
 *   SHEET_WEBHOOK=... node scripts/refresh-roles.mjs --check    verify only, never write
 *
 * content/roles-fallback.json is what /careers renders when the Apps Script
 * endpoint is unreachable, or when no webhook is configured at all — which is
 * the state a fresh clone is in.
 *
 * BY HAND, NOT ON A CRON, unlike the episode and stats refreshes. Two reasons.
 * There is no upstream format that can change underneath us, so there is nothing
 * for a scheduled run to catch; and the file is empty most of the time, so a
 * nightly job would mostly be committing "still nothing open" to the history.
 * Run it when a listing goes up or comes down, so that a sheet outage shows the
 * roles rather than a blank page.
 *
 * A DELIBERATELY EMPTY FALLBACK IS A CORRECT ONE. The show is usually not
 * hiring, and "no roles" renders the honest page. Only the day there is
 * something open does an empty fallback become a page that is quietly wrong.
 *
 * Imports lib/roles-sheet.ts rather than parsing here, for the same reason
 * refresh-stats.mjs imports lib/channel.ts: a script with its own parser proves
 * some parser can read the sheet, which is not the question. Node strips the
 * TypeScript natively (>= 22.6).
 *
 * roles-sheet.ts and NOT roles.ts. roles.ts imports the fallback JSON, and a
 * JSON import without an import attribute cannot be loaded by plain Node —
 * importing it here fails with ERR_IMPORT_ATTRIBUTE_MISSING before a line of
 * this runs.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { parseRoles } from "../lib/roles-sheet.ts";
import { rolesUrl } from "../lib/sheet.ts";

const OUT = new URL("../content/roles-fallback.json", import.meta.url);
const checkOnly = process.argv.includes("--check");
const WEBHOOK = process.env.SHEET_WEBHOOK ?? process.env.PARTNER_SHEET_WEBHOOK;

if (!WEBHOOK) {
  console.error("SHEET_WEBHOOK is not set.");
  console.error("It is the Apps Script /exec URL — see scripts/sheet-webhook.gs,");
  console.error("which carries the whole setup at the top of the file.");
  process.exitCode = 1;
}

if (WEBHOOK) {
  let res;
  try {
    // The same URL builder the site uses, so a change to the endpoint cannot
    // leave the script checking something the page does not read.
    res = await fetch(rolesUrl(WEBHOOK), { redirect: "follow" });
  } catch (err) {
    console.error(`could not reach the sheet: ${err.message}`);
    process.exitCode = 1;
  }

  if (res) {
    if (!res.ok) {
      console.error(`the endpoint returned HTTP ${res.status}`);
      console.error(await res.text());
      process.exitCode = 1;
    } else {
      const body = await res.json();
      const roles = parseRoles(body);
      const current = JSON.parse(readFileSync(OUT, "utf8"));

      // The rows as the endpoint sent them, not the parsed shape: the fallback
      // then exercises the identical parser the live path does, so a fallback
      // the parser cannot read is caught here rather than the day it is needed.
      const rows = Array.isArray(body?.roles) ? body.roles : [];

      const next = {
        _comment:
          "GENERATED by scripts/refresh-roles.mjs. Cold-start fallback for lib/roles.ts, " +
          "used only when the Apps Script endpoint is unreachable or SHEET_WEBHOOK is unset. " +
          "Re-run the script rather than editing by hand. Rows are the endpoint's own shape, " +
          "so parseRoles reads them exactly as it reads a live response — a fallback the " +
          "parser cannot understand is a fallback that fails the day it is needed.",
        capturedAt: new Date().toISOString().slice(0, 10),
        roles: rows,
      };

      for (const role of roles) {
        console.log(`${role.status.padEnd(7)} ${role.slug}  (${role.title})`);
      }
      console.log(
        `\n${roles.length} role${roles.length === 1 ? "" : "s"} readable, ` +
          `${roles.filter((r) => r.status === "Open").length} open`,
      );
      if (rows.length > roles.length) {
        // Rows the endpoint sent that the parser dropped: a title-less row, or a
        // status nobody recognises. Worth saying out loud, because the second of
        // those hides a listing somebody thinks they published.
        console.log(
          `${rows.length - roles.length} row(s) dropped — check the Title and Status columns.`,
        );
      }

      const same = JSON.stringify(current.roles) === JSON.stringify(next.roles);
      if (same) {
        console.log("fallback already current, nothing to write");
      } else if (checkOnly) {
        console.log("--check: not writing. Run without the flag to update.");
        process.exitCode = 1;
      } else {
        writeFileSync(OUT, `${JSON.stringify(next, null, 2)}\n`);
        console.log(`wrote content/roles-fallback.json (${next.capturedAt})`);
      }
    }
  }
}
